name: Publish to PyPI
on:
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    - uses: actions/checkout@v4
    - run: pip install poetry
    - run: poetry publish --build -u kolypto -p ${{ secrets.PYPI_PASSWORD }}
